version: 0.2

phases:
  install:
    commands:
      - echo "This is the install phase"
  pre_build:
    commands:
      - echo "This is the pre-build phase"
  build:
    commands:
      - echo "This is the build phase"
  post_build:
    commands:
      - echo "This is the post-build phase"
